### ISSUE TITLE
MVVM Pattern With Droid & Touch

### ISSUE THREAD

**Issue by rzee7** [jamesmontemagno/MotzCodesLive#1]
Hello James,

This is Riyaz, working as Xamarin Mobile Developer since It was monotouch or monodroid. I like your all post and samples you made. :)

Here it may be off topic but I'd like to like see a topic about MVVM pattern with droid and touch as you guys used in Kinder Chat app. It would be great if you post a small sample about this.

@jamesmontemagno looking forward to here you back :+1:  

Thanks
Riyaz

**Comment by rzee7** [comment]
Thank you so much @jamesmontemagno :) :100:  
It is the same I was looking and trying :) Keep posting!!

Thanks
RIYAZ

**Comment by vikramboya** [comment]
Hi James,

I am trying to implement a listview with checkbox .But when I select multiple and click on the delete button at the bottom of the page it is not getting deleted and update the list.I tried to implement and serached in Google.But there is no such simple example to explain.I am requesting to provide one small example in the Github and share the link
