### ISSUE TITLE
sqlite-net-pcl or SQLite.Net.Core-PCL

### ISSUE THREAD

**Issue by reader-man** [jamesmontemagno/MotzCodesLive#2]
Hello @jamesmontemagno 
I saw your Video "Motz Codes Live: Let's create a SQLite Database!":
https://www.youtube.com/watch?v=_MX5ZrDAXP8

its a great tutorial, but know after one year, there is these two projects:
https://www.nuget.org/packages/sqlite-net-pcl/
vs
https://www.nuget.org/packages/SQLite.Net.Core-PCL/ 

and i am still confused.
and i want to use Xamarin.Forms for all devices, so can you give me a suggestion if you can?

**Comment by jamesmontemagno** [comment]
https://www.nuget.org/packages/sqlite-net-pcl/ is the official and what I use.
